

spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

---

spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}


# 로컬DB 사용시
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: qhdks2di!
#    url: jdbc:mysql://localhost:3306/pc?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
#    show-sql: true

#spring:
#  datasource:
#    url: jdbc:h2:./data
#  jpa:
#    hibernate:
#      ddl-auto: update
